-- Digital Board schema (PostgreSQL). Applied idempotently on first DB access.
-- Postgres has ADD COLUMN IF NOT EXISTS, so added columns live at the bottom of
-- this file instead of in a migration list in code.

CREATE TABLE IF NOT EXISTS users (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  name          TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  color         TEXT NOT NULL,
  is_admin      INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  position   INTEGER NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS columns (
  id         TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title      TEXT NOT NULL,
  color      TEXT NOT NULL,
  position   INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS columns_project ON columns(project_id, position);

CREATE TABLE IF NOT EXISTS tasks (
  id          TEXT PRIMARY KEY,
  column_id   TEXT NOT NULL REFERENCES columns(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  description TEXT,
  label       TEXT,
  priority    TEXT NOT NULL DEFAULT 'medium',
  assignee_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  due_date    TEXT,
  position    INTEGER NOT NULL,
  created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS tasks_column ON tasks(column_id, position);
CREATE INDEX IF NOT EXISTS tasks_assignee ON tasks(assignee_id);

-- BY DEFAULT rather than ALWAYS: bulk restores write explicit ids.
CREATE TABLE IF NOT EXISTS task_events (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id  TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  actor_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  text     TEXT NOT NULL,
  at       TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS task_events_task ON task_events(task_id, id);

CREATE TABLE IF NOT EXISTS canvases (
  id         TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  position   INTEGER NOT NULL,
  snapshot   TEXT,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS canvases_project ON canvases(project_id, position);

CREATE TABLE IF NOT EXISTS messages (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- NULL = the workspace channel; a user id = a direct message to that person.
  recipient_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  body         TEXT NOT NULL,
  created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS messages_channel ON messages(recipient_id, id);
CREATE INDEX IF NOT EXISTS messages_dm ON messages(author_id, recipient_id, id);

-- Per-conversation read cursor. channel = 'all' for the workspace channel,
-- otherwise the other person's user id.
CREATE TABLE IF NOT EXISTS message_reads (
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel      TEXT NOT NULL,
  last_read_id INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, channel)
);

CREATE TABLE IF NOT EXISTS attachments (
  id         TEXT PRIMARY KEY,
  message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  mime       TEXT NOT NULL,
  size       INTEGER NOT NULL,
  data       BYTEA NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS attachments_message ON attachments(message_id);

-- Columns added after the first release. Append only.
ALTER TABLE users    ADD COLUMN IF NOT EXISTS last_seen_at TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS edited_at    TEXT;
ALTER TABLE tasks    ADD COLUMN IF NOT EXISTS description  TEXT;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS data BYTEA;
