-- Digital Board schema (PostgreSQL). Applied idempotently on first DB access.
-- Postgres has ADD COLUMN IF NOT EXISTS, so added columns live at the bottom of
-- this file instead of in a migration list in code.

CREATE TABLE IF NOT EXISTS users (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  name          TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  color         TEXT NOT NULL,
  is_admin      INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  position   INTEGER NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS columns (
  id         TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title      TEXT NOT NULL,
  color      TEXT NOT NULL,
  position   INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS columns_project ON columns(project_id, position);

CREATE TABLE IF NOT EXISTS project_members (
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role       TEXT NOT NULL CHECK (role IN ('admin', 'editor', 'viewer')),
  PRIMARY KEY (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS tasks (
  id          TEXT PRIMARY KEY,
  column_id   TEXT NOT NULL REFERENCES columns(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  description TEXT,
  label       TEXT,
  priority    TEXT NOT NULL DEFAULT 'medium',
  assignee_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  due_date    TEXT,
  position    INTEGER NOT NULL,
  created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS tasks_column ON tasks(column_id, position);
CREATE INDEX IF NOT EXISTS tasks_assignee ON tasks(assignee_id);

-- BY DEFAULT rather than ALWAYS: bulk restores write explicit ids.
CREATE TABLE IF NOT EXISTS task_events (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id  TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  actor_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  text     TEXT NOT NULL,
  at       TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS task_events_task ON task_events(task_id, id);

CREATE TABLE IF NOT EXISTS canvases (
  id         TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  position   INTEGER NOT NULL,
  snapshot   TEXT,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS canvases_project ON canvases(project_id, position);

CREATE TABLE IF NOT EXISTS messages (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- NULL = the workspace channel; a user id = a direct message to that person.
  recipient_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  body         TEXT NOT NULL,
  created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS messages_channel ON messages(recipient_id, id);
CREATE INDEX IF NOT EXISTS messages_dm ON messages(author_id, recipient_id, id);

-- Per-conversation read cursor. channel = 'all' for the workspace channel,
-- otherwise the other person's user id.
CREATE TABLE IF NOT EXISTS message_reads (
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel      TEXT NOT NULL,
  last_read_id INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, channel)
);

CREATE TABLE IF NOT EXISTS attachments (
  id         TEXT PRIMARY KEY,
  message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  mime       TEXT NOT NULL,
  size       INTEGER NOT NULL,
  data       BYTEA NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS attachments_message ON attachments(message_id);

CREATE TABLE IF NOT EXISTS activity_reads (
  user_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_id INTEGER NOT NULL REFERENCES task_events(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, event_id)
);

-- Columns added after the first release. Append only.
ALTER TABLE users    ADD COLUMN IF NOT EXISTS last_seen_at TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS edited_at    TEXT;
ALTER TABLE tasks    ADD COLUMN IF NOT EXISTS description  TEXT;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS data BYTEA;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_activity_read_id INTEGER NOT NULL DEFAULT 0;

-- ── Multi-workspace ─────────────────────────────────────────────────────────
-- Tenancy is carried by three columns. Everything under a project (columns,
-- tasks, task_events, canvases) reaches its workspace through projects, and
-- attachments / message_reads reach it through messages and users, so those
-- tables need no column of their own.
CREATE TABLE IF NOT EXISTS workspaces (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  created_at TEXT NOT NULL
);

ALTER TABLE users    ADD COLUMN IF NOT EXISTS workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE;

-- Backfill for an install that predates workspaces: everything it holds is, by
-- definition, one workspace. Named from the old settings row. Runs once —
-- the guard is "some row still has no workspace_id".
INSERT INTO workspaces (id, name, created_at)
SELECT 'ws-legacy', COALESCE((SELECT value FROM settings WHERE key = 'workspace'), 'Workspace'), now()::text
 WHERE EXISTS (SELECT 1 FROM users WHERE workspace_id IS NULL)
   AND NOT EXISTS (SELECT 1 FROM workspaces WHERE id = 'ws-legacy');

UPDATE users    SET workspace_id = 'ws-legacy' WHERE workspace_id IS NULL;
UPDATE projects SET workspace_id = 'ws-legacy' WHERE workspace_id IS NULL;
UPDATE messages SET workspace_id = 'ws-legacy' WHERE workspace_id IS NULL;

CREATE INDEX IF NOT EXISTS users_workspace    ON users(workspace_id);
CREATE INDEX IF NOT EXISTS projects_workspace ON projects(workspace_id, position);
CREATE INDEX IF NOT EXISTS messages_workspace ON messages(workspace_id, recipient_id, id);

-- Email stays globally unique on purpose. One address is one account in one
-- workspace, which keeps sign-in a single lookup with no "which workspace?"
-- step. Registering with an address that already exists is refused.
